name: flutter_shop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/category_icons/
    - assets/fonts/
